### ISSUE TITLE
The official distribution of SimpleEnunu has already been installed the older Pytorch

### ISSUE THREAD

**Issue by taroushirani** [oatsu-gh/SimpleEnunu#2]
Hello, I found that the official distribution of SimpleEnunu has been installed the older version of pytorch( 1.9.1+cpu), and ltt_install_torch never  be called.

**Comment by oatsu-gh** [comment]
Thank you. I'll check and fix it.

**Comment by oatsu-gh** [comment]
Fixed in v0.2.1
